hn_config.settings:
  type: config_object
  label: 'HN Config Settings'
  mapping:
    menus:
      type: sequence
      label: 'Menus'
      sequence:
        type: string
    entities:
      type: sequence
      label: 'Config entities'
      sequence:
        type: string
