hn_cleaner.settings:
  type: config_object
  label: 'HN Strip Fields Settings'
  mapping:
    fields:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
    entities:
      type: sequence
      sequence:
        type: string
