pvm_settings.config:
  path: '/admin/config/pvm'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSettingsForm'
    _title: 'PvM Settings'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.social:
  path: '/admin/config/pvm/social'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSocialSettingsForm'
    _title: 'Social Settings'
  requirements:
    _permission: 'administer site configuration'
