pvm_settings.config:
  path: '/admin/config/pvm'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSettingsForm'
    _title: 'PvM Settings'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.menu:
  path: '/admin/config/pvm/menu'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmMenuSettingsForm'
    _title: 'PvM settings menu'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.logo:
  path: '/admin/config/pvm/logo'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmLogoSettingsForm'
    _title: 'PvM settings logo'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.qa:
  path: '/admin/config/pvm/qa'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmQASettingsForm'
    _title: 'PvM settings QA'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.social:
  path: '/admin/config/pvm/social'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSocialSettingsForm'
    _title: 'PvM settings social'
  requirements:
    _permission: 'administer site configuration'
