pvm_settings.config:
  title: 'PvM Settings'
  description: 'Configuration for site specific elements'
  parent: system.admin_config
  route_name: pvm_settings.config
  weight: 100

pvm_settings.config.socialchannels:
  title: 'Social channels'
  description: 'Social channels related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.socialchannels
  weight: 1

pvm_settings.config.socialchannels:
  title: 'Social sharing'
  description: 'Social sharing related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.socialchannels
  weight: 2

