pvm_settings.config:
  path: '/admin/config/pvm'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSettingsForm'
    _title: 'PvM Settings'
  requirements:
    _permission: 'administer site configuration'
