pvm_settings.config:
  route_name: pvm_settings.config
  base_route: pvm_settings.config
  title: General
pvm_settings.config.menu:
  route_name: pvm_settings.config.menu
  base_route: pvm_settings.config
  title: Menu
pvm_settings.config.logo:
  route_name: pvm_settings.config.logo
  base_route: pvm_settings.config
  title: Logo
pvm_settings.config.qa:
  route_name: pvm_settings.config.qa
  base_route: pvm_settings.config
  title: Q&A
pvm_settings.config.social:
  route_name: pvm_settings.config.social
  base_route: pvm_settings.config
  title: Social
