pvm_settings.config:
  title: 'PvM Settings'
  description: 'Configuration for site specific elements'
  parent: system.admin_config
  route_name: pvm_settings.config
  weight: 100

pvm_settings.config.social:
  title: 'Social'
  description: 'Social media related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.social
  weight: 100
