pvm_settings.config:
  path: '/admin/config/pvm'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSettingsForm'
    _title: 'PvM Settings'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.socialchannels:
  path: '/admin/config/pvm/social-channels'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSocialChannelsSettingsForm'
    _title: 'Social Channels Settings'
  requirements:
    _permission: 'administer site configuration'

pvm_settings.config.socialsharing:
  path: '/admin/config/pvm/social-sharing'
  defaults:
    _form: '\Drupal\pvm_settings\Form\PvmSocialSharingSettingsForm'
    _title: 'Social Sharing Settings'
  requirements:
    _permission: 'administer site configuration'

