pvm_settings.config:
  title: 'PvM Settings'
  description: 'Configuration for site specific elements'
  parent: system.admin
  route_name: pvm_settings.config
  weight: 100

pvm_settings.config.general:
  title: 'General'
  description: 'General configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config
  weight: 1

pvm_settings.config.menu:
  title: 'Menu'
  description: 'Menu related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.menu
  weight: 2

pvm_settings.config.logo:
  title: 'Logo'
  description: 'Logo related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.logo
  weight: 3

pvm_settings.config.qa:
  title: 'QA'
  description: 'QA related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.qa
  weight: 4

pvm_settings.config.social:
  title: 'Social'
  description: 'Social channels related configuration'
  parent: pvm_settings.config
  route_name: pvm_settings.config.social
  weight: 5