name: Headless Ninja REST - Configuration data
type: module
description: This adds config files to the response, like menu's, translations and arbitrary Drupal config.
package: Headless Ninja
core: 8.x

dependencies:
  - hn
