hn_config.admin:
  path: '/admin/config/services/hn/config'
  defaults:
    _form: '\Drupal\hn_config\Form\SettingsForm'
    _title: 'Headless Ninja Config Settings'
  requirements:
    _permission: 'administer hn'
