api_settings.config.config:
  route_name: api_settings.config
  base_route: api_settings.config
  title: General
api_settings.config.menu:
  route_name: api_settings.menu
  base_route: api_settings.config
  title: Menu
api_settings.config.logo:
  route_name: api_settings.logo
  base_route: api_settings.config
  title: Logo
api_settings.config.qa:
  route_name: api_settings.qa
  base_route: api_settings.config
  title: Q&A
api_settings.config.social:
  route_name: api_settings.social
  base_route: api_settings.config
  title: Social
