<?php

/**
 * @file
 * Contains api_settings.module..
 */

use \Drupal\api_settings\Helpers\Language;
use \Drupal\api_settings\Helpers\Menu;


/**
 * Implements hook_help().
 */
function api_settings_help($route_name) {
  switch ($route_name) {
    // Main module help for the api_settings module.
    case 'help.page.api_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Endpoint that returns all the settings that a user needs on every page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function api_settings_install() {
  $config = \Drupal::configFactory()->get('api_settings.general');

  $hooks = array('menu', 'language');
  $hookTypes = $config->get('hookTypes');

  if (!empty($hookTypes) && is_array($hookTypes)) {
    $hooks = array_merge($hooks + $hookTypes);
  }

  $config = \Drupal::configFactory()->getEditable('api_settings.general');

  $config->set('hookTypes', $hooks);
  $config->save();
}

/**
 * Implements hook_api_alter_settings_data_HOOK_TYPE() 'menu'.
 */
function api_settings_api_alter_settings_data_menu(&$responseArray) {
  $responseArray['menu'] = Menu::get();
}

/**
 * Implements hook_api_alter_settings_data_HOOK_TYPE() for 'language'.
 */
function api_settings_api_alter_settings_data_language(&$responseArray) {
  $responseArray['language'] = Language::getLanguages();
}
