<?php

/**
 * @file
 * Contains api_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function api_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the api_settings module.
    case 'help.page.api_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Endpoint that returns all the settings that a user needs on every page') . '</p>';
      return $output;

    default:
  }
}
