api_settings.config:
  path: '/admin/config/services/settings-api'
  defaults:
    _form: '\Drupal\api_settings\Form\ApiSettingsForm'
    _title: 'Settings API settings'
  requirements:
    _permission: 'administer site configuration'

api_settings.qa:
  path: '/admin/config/services/settings-api/qa'
  defaults:
    _form: '\Drupal\api_settings\Form\QASettingsForm'
    _title: 'Settings API settings'
  requirements:
    _permission: 'administer site configuration'
