<?php

/**
 * @file
 * Contains hn_views.module..
 */


/**
 * Implements hook_help().
 */
function hn_views_help($route_name) {
  switch ($route_name) {
    // Main module help for the pvm_hn_views module.
    case 'help.page.hn_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This serializer adds everything you need to a rest export view.') . '</p>';
      return $output;

    default:
  }
}
