<?php

/**
 * @file
 * Contains api_menu.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function api_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the api_menu module.
    case 'help.page.api_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Endpoint for menu') . '</p>';
      return $output;

    default:
  }
}
